# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
inherit_from:
  - .rubocop_todo.yml

AllCops:
  NewCops: enable

# We use `gems.rb` in this project
Bundler/GemFilename:
  EnforcedStyle: gems.rb

# Totally disable this check
# since we don't initialize class directly in spec
# and checking of one class can be split into different specs
RSpec/DescribeClass:
  Enabled: false
