# frozen_string_literal: true

require 'onlyoffice_webdriver_wrapper'
require_relative 'testing_site_onlyoffice/config'
require_relative 'testing_site_onlyoffice/site_test_instance'
require_relative 'testing_site_onlyoffice/site_home_page'
require_relative 'testing_site_onlyoffice/convert_page'
require_relative 'testing_site_onlyoffice/for_business/site_for_business_integrations_helper'
