require_relative '../lib/testing_site_onlyoffice'
require_relative '../shared_examples/commercial_installer_download'
require_relative '../shared_examples/document_builder_version_and_realise_date'
require 'onlyoffice_testrail_wrapper'
require 'rspec'
