name: Linting
on:
  - pull_request
jobs:
  yamllint:
    name: Yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Yamllint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '20'
      - name: Check markdown files using `markdownlint`
        run: |
          npm install -g markdownlint-cli
          markdownlint *.md
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up latest stable ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
      - name: Setup rubocop
        run: |
          bundle config set with 'development'
          bundle install
      - name: Run Rubocop
        run: bundle exec rubocop
